all:
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: /home/noe.jobard/Documents/devops/ansible/id_rsa
    POSTGRES_DB: db
    POSTGRES_USER: usr
    POSTGRES_PASSWORD: pwd
  children:
    prod:
      hosts:
        centos@noe.jobard.takima.cloud
