all:
  vars:
    ansible_user: centos
    POSTGRES_DB: db
    POSTGRES_USER: usr
    POSTGRES_PASSWORD: pwd
    POSTGRES_HOSTNAME: postgres
    network: app_network
  children:
    prod:
      hosts:
        centos@noe.jobard.takima.cloud
