name: CI devops build and push Docker image
on:
  workflow_run:
    workflows: ["CI devops test backend"]
    branches: [main]
    types:
      - completed
jobs:
  build-and-push-docker-image:
    name: "Build and push Docker image"
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.LOGIN }} -p ${{ secrets.MDP }}
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./webserver2
          tags: ${{secrets.LOGIN}}/devops-backend:1.0.0
          push: true
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{secrets.LOGIN}}/devops-database:1.0.0
          push: true
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http_server
          tags: ${{secrets.LOGIN}}/devops-httpd:1.0.0
          push: true
      - name: Build image and push front
        uses: docker/build-push-action@v3
        with:
          context: ./devops-front-main
          tags: ${{secrets.LOGIN}}/devops-front-main:1.0.0
          push: true